# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efb48a2affb3fbd707a9575c86c3be927b8a0e4740e79608af981b4c0a4efab267ce6594691a9a784afeba4f0f79968a211528f311da9e23c5cfbe2bea6b416f

test:
  secret_key_base: 8889ed9d555e14887088b37c5ac54cd673bed7916c079bcbf19aea4b6a06447a3f861095b1b4e60f88d03b4d206c12f921edf81d1f97200321cc7c114d77f98e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
